export type {
    SearchCapabilityState,
    DefaultSearchCapabilityState,
    WithFuzzy,
    WithTagger,
    MergeSearchCapability,
    AvailableTags,
    FuzzyPaths,
    FuzzyField,
    FuzzyOrder,
    FuzzyQueryInput,
    FuzzyConfig,
    TagFilter,
    TaggerRule,
    TaggerConfig,
    SearchQuery,
    SearchInput,
} from "@/types/search";
